"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 07:53:28.088588
"""
from alembic import op
import sqlalchemy as sa
import app.models.base


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=60), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_keys')),
    sa.UniqueConstraint('scope', 'key', name=op.f('uq_idempotency_keys_scope_key'))
    )
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_table('payment_webhook_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('received_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('processed_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_webhook_events')),
    sa.UniqueConstraint('provider', 'event_id', name=op.f('uq_payment_webhook_events_provider_event_id'))
    )
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('clubs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('brand_color', sa.String(length=16), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_clubs_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clubs'))
    )
    op.create_index(op.f('ix_clubs_organization_id'), 'clubs', ['organization_id'], unique=False)
    op.create_table('coupons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('discount_type', sa.String(length=8), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("discount_type IN ('PERCENT','FLAT')", name=op.f('ck_coupons_discount_type')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_coupons_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupons')),
    sa.UniqueConstraint('organization_id', 'code', name=op.f('uq_coupons_organization_id_code'))
    )
    op.create_table('expense_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_expense_categories_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense_categories')),
    sa.UniqueConstraint('organization_id', 'code', name=op.f('uq_expense_categories_organization_id_code'))
    )
    op.create_table('game_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('default_hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_game_types_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_types')),
    sa.UniqueConstraint('organization_id', 'code', name=op.f('uq_game_types_organization_id_code'))
    )
    op.create_table('membership_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('included_minutes', sa.Integer(), nullable=False),
    sa.Column('deduction_block_minutes', sa.Integer(), nullable=False),
    sa.Column('table_discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('product_discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('game_type_ids', sa.JSON(), nullable=True),
    sa.Column('max_minutes_per_day', sa.Integer(), nullable=True),
    sa.Column('benefits', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_membership_plans_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_membership_plans')),
    sa.UniqueConstraint('organization_id', 'code', name=op.f('uq_membership_plans_organization_id_code'))
    )
    op.create_table('notification_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=160), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_notification_templates_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_templates')),
    sa.UniqueConstraint('organization_id', 'event', 'channel', name=op.f('uq_notification_templates_organization_id_event_channel'))
    )
    op.create_table('product_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_product_categories_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_categories')),
    sa.UniqueConstraint('organization_id', 'name', name=op.f('uq_product_categories_organization_id_name'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_roles_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('organization_id', 'code', name=op.f('uq_roles_organization_id_code'))
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_suppliers_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    op.create_table('branches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('club_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('timezone', sa.String(length=40), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('opening_time', sa.String(length=5), nullable=False),
    sa.Column('closing_time', sa.String(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_branches_club_id_clubs')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_branches_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches')),
    sa.UniqueConstraint('organization_id', 'code', name=op.f('uq_branches_organization_id_code'))
    )
    op.create_index(op.f('ix_branches_club_id'), 'branches', ['club_id'], unique=False)
    op.create_index(op.f('ix_branches_organization_id'), 'branches', ['organization_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('track_stock', sa.Boolean(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.CheckConstraint('price >= 0', name=op.f('ck_products_price')),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], name=op.f('fk_products_category_id_product_categories')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_products_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('organization_id', 'sku', name=op.f('uq_products_organization_id_sku'))
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('home_branch_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('preferred_game_type_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_visits', sa.Integer(), nullable=False),
    sa.Column('total_spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_play_minutes', sa.Integer(), nullable=False),
    sa.Column('last_visit_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('loyalty_points', sa.Integer(), nullable=False),
    sa.Column('referral_code', sa.String(length=12), nullable=True),
    sa.Column('referred_by_id', sa.Uuid(), nullable=True),
    sa.Column('marketing_opt_in', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['home_branch_id'], ['branches.id'], name=op.f('fk_customers_home_branch_id_branches')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_customers_organization_id_organizations')),
    sa.ForeignKeyConstraint(['preferred_game_type_id'], ['game_types.id'], name=op.f('fk_customers_preferred_game_type_id_game_types')),
    sa.ForeignKeyConstraint(['referred_by_id'], ['customers.id'], name=op.f('fk_customers_referred_by_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('organization_id', 'phone', name=op.f('uq_customers_organization_id_phone')),
    sa.UniqueConstraint('referral_code', name=op.f('uq_customers_referral_code'))
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_organization_id'), 'customers', ['organization_id'], unique=False)
    op.create_table('document_sequences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=8), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_document_sequences_branch_id_branches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_sequences')),
    sa.UniqueConstraint('branch_id', 'name', 'period', name=op.f('uq_document_sequences_branch_id_name_period'))
    )
    op.create_table('holidays',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_holidays_branch_id_branches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holidays')),
    sa.UniqueConstraint('branch_id', 'day', name=op.f('uq_holidays_branch_id_day'))
    )
    op.create_index(op.f('ix_holidays_branch_id'), 'holidays', ['branch_id'], unique=False)
    op.create_table('stock_levels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_stock_levels_branch_id_branches')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_levels_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_levels')),
    sa.UniqueConstraint('branch_id', 'product_id', name=op.f('uq_stock_levels_branch_id_product_id'))
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_system_settings_branch_id_branches')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_system_settings_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings')),
    sa.UniqueConstraint('organization_id', 'branch_id', 'key', name=op.f('uq_system_settings_organization_id_branch_id_key'))
    )
    op.create_table('tables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('game_type_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('peak_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('off_peak_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('minimum_booking_duration', sa.Integer(), nullable=False),
    sa.Column('maximum_booking_duration', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_online_bookable', sa.Boolean(), nullable=False),
    sa.Column('qr_token', sa.String(length=40), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status_changed_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('AVAILABLE', 'RESERVED', 'OCCUPIED', 'GAME_STARTED', 'PAUSED', 'MAINTENANCE', 'BLOCKED')", name=op.f('ck_tables_status')),
    sa.CheckConstraint('maximum_booking_duration >= minimum_booking_duration', name=op.f('ck_tables_max_duration')),
    sa.CheckConstraint('minimum_booking_duration > 0', name=op.f('ck_tables_min_duration')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_tables_branch_id_branches')),
    sa.ForeignKeyConstraint(['game_type_id'], ['game_types.id'], name=op.f('fk_tables_game_type_id_game_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tables')),
    sa.UniqueConstraint('branch_id', 'table_number', name=op.f('uq_tables_branch_id_table_number')),
    sa.UniqueConstraint('qr_token', name=op.f('uq_tables_qr_token'))
    )
    op.create_index(op.f('ix_tables_branch_id'), 'tables', ['branch_id'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('game_type_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=14), nullable=False),
    sa.Column('entry_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('prize_pool', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('group_count', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('winner_player_id', sa.Uuid(), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("format IN ('KNOCKOUT', 'ROUND_ROBIN', 'GROUPS_KNOCKOUT')", name=op.f('ck_tournaments_format')),
    sa.CheckConstraint("status IN ('DRAFT', 'REGISTRATION', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')", name=op.f('ck_tournaments_status')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_tournaments_branch_id_branches')),
    sa.ForeignKeyConstraint(['game_type_id'], ['game_types.id'], name=op.f('fk_tournaments_game_type_id_game_types')),
    sa.ForeignKeyConstraint(['winner_player_id'], ['tournament_players.id'], name=op.f('fk_tournaments_winner_player_id_tournament_players'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournaments'))
    )
    op.create_index(op.f('ix_tournaments_branch_id'), 'tournaments', ['branch_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.String(length=60), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('device_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('last_seen_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('firmware_version', sa.String(length=30), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('api_key_prefix', sa.String(length=8), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("device_type IN ('RFID_READER', 'NFC_READER', 'QR_CODE', 'MOTION_SENSOR', 'PRESSURE_SENSOR', 'IR_SENSOR', 'VIBRATION_SENSOR', 'CAMERA', 'TABLE_CONTROLLER', 'CUSTOM')", name=op.f('ck_devices_device_type')),
    sa.CheckConstraint("status IN ('ONLINE', 'OFFLINE', 'ERROR', 'MAINTENANCE')", name=op.f('ck_devices_status')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_devices_branch_id_branches')),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name=op.f('fk_devices_table_id_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('device_id', name=op.f('uq_devices_device_id'))
    )
    op.create_index(op.f('ix_devices_branch_id'), 'devices', ['branch_id'], unique=False)
    op.create_index(op.f('ix_devices_table_id'), 'devices', ['table_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('card_uid', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=False),
    sa.Column('minutes_total', sa.Integer(), nullable=False),
    sa.Column('minutes_used', sa.Integer(), nullable=False),
    sa.Column('price_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expiry_notified_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'EXPIRED', 'SUSPENDED', 'CANCELLED')", name=op.f('ck_memberships_status')),
    sa.CheckConstraint('minutes_used >= 0', name=op.f('ck_memberships_minutes_used')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_memberships_branch_id_branches')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_memberships_customer_id_customers')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_memberships_organization_id_organizations')),
    sa.ForeignKeyConstraint(['plan_id'], ['membership_plans.id'], name=op.f('fk_memberships_plan_id_membership_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('card_uid', name=op.f('uq_memberships_card_uid')),
    sa.UniqueConstraint('code', name=op.f('uq_memberships_code'))
    )
    op.create_index(op.f('ix_memberships_customer_id'), 'memberships', ['customer_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('recipient', sa.String(length=160), nullable=False),
    sa.Column('subject', sa.String(length=160), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=300), nullable=True),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('sent_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.CheckConstraint("channel IN ('EMAIL', 'SMS', 'WHATSAPP', 'PUSH')", name=op.f('ck_notifications_channel')),
    sa.CheckConstraint("status IN ('QUEUED', 'SENT', 'FAILED', 'SKIPPED')", name=op.f('ck_notifications_status')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_notifications_branch_id_branches')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_notifications_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_notifications_dedupe_key'))
    )
    op.create_index('ix_notifications_status', 'notifications', ['status', 'created_at'], unique=False)
    op.create_table('pricing_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('game_type_id', sa.Uuid(), nullable=True),
    sa.Column('table_id', sa.Uuid(), nullable=True),
    sa.Column('day_type', sa.String(length=10), nullable=False),
    sa.Column('days_of_week', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.String(length=5), nullable=True),
    sa.Column('end_time', sa.String(length=5), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('customer_segment', sa.String(length=12), nullable=False),
    sa.Column('rate_per_hour', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rate_multiplier', sa.Float(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("customer_segment IN ('ANY','MEMBER','NON_MEMBER')", name=op.f('ck_pricing_rules_segment')),
    sa.CheckConstraint("day_type IN ('ANY','WEEKDAY','WEEKEND','HOLIDAY')", name=op.f('ck_pricing_rules_day_type')),
    sa.CheckConstraint('rate_per_hour IS NOT NULL OR rate_multiplier IS NOT NULL', name=op.f('ck_pricing_rules_has_price')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_pricing_rules_branch_id_branches')),
    sa.ForeignKeyConstraint(['game_type_id'], ['game_types.id'], name=op.f('fk_pricing_rules_game_type_id_game_types')),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name=op.f('fk_pricing_rules_table_id_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pricing_rules'))
    )
    op.create_index(op.f('ix_pricing_rules_branch_id'), 'pricing_rules', ['branch_id'], unique=False)
    op.create_table('tournament_players',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('group_no', sa.Integer(), nullable=True),
    sa.Column('fee_paid', sa.Boolean(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('frames_for', sa.Integer(), nullable=False),
    sa.Column('frames_against', sa.Integer(), nullable=False),
    sa.Column('eliminated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_tournament_players_customer_id_customers')),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_tournament_players_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournament_players')),
    sa.UniqueConstraint('tournament_id', 'customer_id', name=op.f('uq_tournament_players_tournament_id_customer_id'))
    )
    op.create_index(op.f('ix_tournament_players_tournament_id'), 'tournament_players', ['tournament_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('last_login_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_users_customer_id_customers')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('organization_id', 'username', name=op.f('uq_users_organization_id_username'))
    )
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_audit_logs_branch_id_branches')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_logs_organization_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_branch_time', 'audit_logs', ['branch_id', 'created_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('start_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('end_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('hold_expires_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('booking_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=16), nullable=False),
    sa.Column('coupon_code', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('checked_in_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.String(length=300), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rescheduled_from_id', sa.Uuid(), nullable=True),
    sa.Column('reminder_sent_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("payment_status IN ('PENDING', 'AUTHORIZED', 'PAID', 'PARTIALLY_PAID', 'FAILED', 'REFUNDED', 'CANCELLED')", name=op.f('ck_bookings_payment_status')),
    sa.CheckConstraint("source IN ('ONLINE', 'STAFF', 'PHONE', 'TOURNAMENT')", name=op.f('ck_bookings_source')),
    sa.CheckConstraint("status IN ('HELD', 'CONFIRMED', 'CHECKED_IN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'EXPIRED', 'NO_SHOW')", name=op.f('ck_bookings_status')),
    sa.CheckConstraint('deposit_amount >= 0 AND booking_amount >= 0', name=op.f('ck_bookings_amounts')),
    sa.CheckConstraint('end_at > start_at', name=op.f('ck_bookings_time_order')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_bookings_branch_id_branches')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_bookings_created_by_id_users')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_bookings_customer_id_customers')),
    sa.ForeignKeyConstraint(['rescheduled_from_id'], ['bookings.id'], name=op.f('fk_bookings_rescheduled_from_id_bookings')),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name=op.f('fk_bookings_table_id_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings')),
    sa.UniqueConstraint('reference', name=op.f('uq_bookings_reference'))
    )
    op.create_index('ix_bookings_branch_start', 'bookings', ['branch_id', 'start_at'], unique=False)
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_index('ix_bookings_status_hold', 'bookings', ['status', 'hold_expires_at'], unique=False)
    op.create_index('ix_bookings_table_window', 'bookings', ['table_id', 'start_at', 'end_at'], unique=False)
    op.create_table('device_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_pk', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('received_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.String(length=40), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_device_events_branch_id_branches')),
    sa.ForeignKeyConstraint(['device_pk'], ['devices.id'], name=op.f('fk_device_events_device_pk_devices')),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name=op.f('fk_device_events_table_id_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_events')),
    sa.UniqueConstraint('device_pk', 'event_id', name=op.f('uq_device_events_device_pk_event_id'))
    )
    op.create_index('ix_device_events_table_time', 'device_events', ['table_id', 'occurred_at'], unique=False)
    op.create_table('device_heartbeats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_pk', sa.Uuid(), nullable=False),
    sa.Column('received_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('firmware_version', sa.String(length=30), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.Column('queue_depth', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['device_pk'], ['devices.id'], name=op.f('fk_device_heartbeats_device_pk_devices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_heartbeats'))
    )
    op.create_index('ix_device_heartbeats_device_time', 'device_heartbeats', ['device_pk', 'received_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('issued_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('open_key', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('opened_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('closed_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('opening_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cash_sales', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cash_expenses', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('counted_cash', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('variance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('OPEN', 'CLOSED')", name=op.f('ck_shifts_status')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_shifts_branch_id_branches')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shifts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shifts')),
    sa.UniqueConstraint('open_key', name=op.f('uq_shifts_open_key'))
    )
    op.create_index(op.f('ix_shifts_branch_id'), 'shifts', ['branch_id'], unique=False)
    op.create_table('table_detection_states',
    sa.Column('table_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('first_activity_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('activity_events', sa.Integer(), nullable=False),
    sa.Column('identified_customer_id', sa.Uuid(), nullable=True),
    sa.Column('identified_membership_id', sa.Uuid(), nullable=True),
    sa.Column('identified_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('IDLE', 'ACTIVITY_DETECTED', 'CONFIRMING', 'GAME_STARTED')", name=op.f('ck_table_detection_states_state')),
    sa.ForeignKeyConstraint(['identified_customer_id'], ['customers.id'], name=op.f('fk_table_detection_states_identified_customer_id_customers')),
    sa.ForeignKeyConstraint(['identified_membership_id'], ['memberships.id'], name=op.f('fk_table_detection_states_identified_membership_id_memberships')),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name=op.f('fk_table_detection_states_table_id_tables'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('table_id', name=op.f('pk_table_detection_states'))
    )
    op.create_table('tournament_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=10), nullable=False),
    sa.Column('round_no', sa.Integer(), nullable=False),
    sa.Column('match_no', sa.Integer(), nullable=False),
    sa.Column('group_no', sa.Integer(), nullable=True),
    sa.Column('player1_id', sa.Uuid(), nullable=True),
    sa.Column('player2_id', sa.Uuid(), nullable=True),
    sa.Column('score1', sa.Integer(), nullable=True),
    sa.Column('score2', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Uuid(), nullable=True),
    sa.Column('table_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('next_match_id', sa.Uuid(), nullable=True),
    sa.Column('next_slot', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'WALKOVER')", name=op.f('ck_tournament_matches_status')),
    sa.ForeignKeyConstraint(['next_match_id'], ['tournament_matches.id'], name=op.f('fk_tournament_matches_next_match_id_tournament_matches')),
    sa.ForeignKeyConstraint(['player1_id'], ['tournament_players.id'], name=op.f('fk_tournament_matches_player1_id_tournament_players')),
    sa.ForeignKeyConstraint(['player2_id'], ['tournament_players.id'], name=op.f('fk_tournament_matches_player2_id_tournament_players')),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name=op.f('fk_tournament_matches_table_id_tables')),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_tournament_matches_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['tournament_players.id'], name=op.f('fk_tournament_matches_winner_id_tournament_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournament_matches')),
    sa.UniqueConstraint('tournament_id', 'stage', 'round_no', 'match_no', name=op.f('uq_tournament_matches_tournament_id_stage_round_no_match_no'))
    )
    op.create_index(op.f('ix_tournament_matches_tournament_id'), 'tournament_matches', ['tournament_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_user_roles_branch_id_branches')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', 'branch_id', name=op.f('uq_user_roles_user_id_role_id_branch_id'))
    )
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('booking_holds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('released_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_booking_holds_booking_id_bookings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_holds'))
    )
    op.create_index(op.f('ix_booking_holds_booking_id'), 'booking_holds', ['booking_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('paid_to', sa.String(length=120), nullable=True),
    sa.Column('method', sa.String(length=12), nullable=False),
    sa.Column('shift_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('is_void', sa.Boolean(), nullable=False),
    sa.Column('void_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_expenses_amount')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_expenses_branch_id_branches')),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], name=op.f('fk_expenses_category_id_expense_categories')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_expenses_created_by_id_users')),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_expenses_shift_id_shifts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index('ix_expenses_branch_date', 'expenses', ['branch_id', 'expense_date'], unique=False)
    op.create_table('game_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('membership_id', sa.Uuid(), nullable=True),
    sa.Column('active_table_key', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('billing_status', sa.String(length=12), nullable=False),
    sa.Column('started_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ended_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('paused_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('total_paused_seconds', sa.Integer(), nullable=False),
    sa.Column('planned_end_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('started_by_id', sa.Uuid(), nullable=True),
    sa.Column('ended_by_id', sa.Uuid(), nullable=True),
    sa.Column('detection_method', sa.String(length=10), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('last_activity_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('player_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("billing_status IN ('NOT_STARTED', 'RUNNING', 'PAUSED', 'STOPPED', 'INVOICED')", name=op.f('ck_game_sessions_billing_status')),
    sa.CheckConstraint("detection_method IN ('MANUAL', 'QR', 'RFID', 'NFC', 'SENSOR', 'CAMERA', 'HYBRID', 'BOOKING')", name=op.f('ck_game_sessions_detection_method')),
    sa.CheckConstraint("status IN ('CREATED', 'ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', 'AUTO_CLOSED')", name=op.f('ck_game_sessions_status')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_game_sessions_booking_id_bookings')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_game_sessions_branch_id_branches')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_game_sessions_customer_id_customers')),
    sa.ForeignKeyConstraint(['ended_by_id'], ['users.id'], name=op.f('fk_game_sessions_ended_by_id_users')),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], name=op.f('fk_game_sessions_membership_id_memberships')),
    sa.ForeignKeyConstraint(['started_by_id'], ['users.id'], name=op.f('fk_game_sessions_started_by_id_users')),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name=op.f('fk_game_sessions_table_id_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_sessions')),
    sa.UniqueConstraint('active_table_key', name=op.f('uq_game_sessions_active_table_key')),
    sa.UniqueConstraint('booking_id', name=op.f('uq_game_sessions_booking_id'))
    )
    op.create_index('ix_game_sessions_branch_started', 'game_sessions', ['branch_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_game_sessions_customer_id'), 'game_sessions', ['customer_id'], unique=False)
    op.create_index('ix_game_sessions_table_status', 'game_sessions', ['table_id', 'status'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('alert_type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=True),
    sa.Column('device_pk', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('acknowledged_by_id', sa.Uuid(), nullable=True),
    sa.Column('acknowledged_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("severity IN ('INFO', 'WARNING', 'CRITICAL')", name=op.f('ck_alerts_severity')),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], name=op.f('fk_alerts_acknowledged_by_id_users')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_alerts_branch_id_branches')),
    sa.ForeignKeyConstraint(['device_pk'], ['devices.id'], name=op.f('fk_alerts_device_pk_devices')),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name=op.f('fk_alerts_session_id_game_sessions')),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name=op.f('fk_alerts_table_id_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index('ix_alerts_branch_open', 'alerts', ['branch_id', 'acknowledged_at'], unique=False)
    op.create_index(op.f('ix_alerts_dedupe_key'), 'alerts', ['dedupe_key'], unique=False)
    op.create_table('membership_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('txn_type', sa.String(length=20), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("txn_type IN ('PURCHASE', 'RENEWAL', 'USAGE', 'USAGE_REVERSAL', 'ADJUSTMENT', 'CANCELLATION')", name=op.f('ck_membership_transactions_txn_type')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_membership_transactions_created_by_id_users')),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], name=op.f('fk_membership_transactions_membership_id_memberships')),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name=op.f('fk_membership_transactions_session_id_game_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_membership_transactions'))
    )
    op.create_index(op.f('ix_membership_transactions_membership_id'), 'membership_transactions', ['membership_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('OPEN', 'INVOICED', 'PAID', 'CANCELLED')", name=op.f('ck_orders_status')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_orders_branch_id_branches')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_orders_created_by_id_users')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_orders_customer_id_customers')),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name=op.f('fk_orders_session_id_game_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('number', name=op.f('uq_orders_number')),
    sa.UniqueConstraint('session_id', name=op.f('uq_orders_session_id'))
    )
    op.create_index(op.f('ix_orders_branch_id'), 'orders', ['branch_id'], unique=False)
    op.create_table('session_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('from_status', sa.String(length=12), nullable=True),
    sa.Column('to_status', sa.String(length=12), nullable=True),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_session_events_actor_id_users')),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name=op.f('fk_session_events_session_id_game_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_events'))
    )
    op.create_index(op.f('ix_session_events_session_id'), 'session_events', ['session_id'], unique=False)
    op.create_table('session_pauses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('paused_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('resumed_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('paused_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['paused_by_id'], ['users.id'], name=op.f('fk_session_pauses_paused_by_id_users')),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name=op.f('fk_session_pauses_session_id_game_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_pauses'))
    )
    op.create_index(op.f('ix_session_pauses_session_id'), 'session_pauses', ['session_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('booking_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('customer_name', sa.String(length=120), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deposit_applied', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('adjustments_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('issued_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('issued_by_id', sa.Uuid(), nullable=True),
    sa.Column('paid_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'ISSUED', 'PARTIALLY_PAID', 'PAID', 'VOID')", name=op.f('ck_invoices_status')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_invoices_booking_id_bookings')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_invoices_branch_id_branches')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_invoices_customer_id_customers')),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], name=op.f('fk_invoices_issued_by_id_users')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_invoices_order_id_orders')),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name=op.f('fk_invoices_session_id_game_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('number', name=op.f('uq_invoices_number')),
    sa.UniqueConstraint('session_id', name=op.f('uq_invoices_session_id'))
    )
    op.create_index('ix_invoices_branch_issued', 'invoices', ['branch_id', 'issued_at'], unique=False)
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('cancel_reason', sa.String(length=200), nullable=True),
    sa.Column('cancelled_by_id', sa.Uuid(), nullable=True),
    sa.Column('added_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_items_qty')),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], name=op.f('fk_order_items_added_by_id_users')),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], name=op.f('fk_order_items_cancelled_by_id_users')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_items_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('approval_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('order_item_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('requested_by_id', sa.Uuid(), nullable=False),
    sa.Column('resolved_by_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.String(length=300), nullable=True),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("approval_type IN ('DISCOUNT', 'CANCEL_ITEM', 'INVOICE_ADJUSTMENT', 'SESSION_ADJUSTMENT', 'REFUND')", name=op.f('ck_approval_requests_approval_type')),
    sa.CheckConstraint("status IN ('PENDING', 'APPROVED', 'REJECTED')", name=op.f('ck_approval_requests_status')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_approval_requests_branch_id_branches')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_approval_requests_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('fk_approval_requests_order_item_id_order_items')),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_approval_requests_requested_by_id_users')),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_approval_requests_resolved_by_id_users')),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name=op.f('fk_approval_requests_session_id_game_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_requests'))
    )
    op.create_index(op.f('ix_approval_requests_branch_id'), 'approval_requests', ['branch_id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('txn_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('order_item_id', sa.Uuid(), nullable=True),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("txn_type IN ('OPENING', 'PURCHASE', 'SALE', 'RETURN', 'SUPPLIER_RETURN', 'DAMAGED', 'ADJUSTMENT', 'SALE_REVERSAL')", name=op.f('ck_inventory_transactions_txn_type')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_inventory_transactions_branch_id_branches')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_inventory_transactions_created_by_id_users')),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('fk_inventory_transactions_order_item_id_order_items')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_transactions_product_id_products')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_inventory_transactions_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_transactions'))
    )
    op.create_index('ix_inventory_txn_branch_product', 'inventory_transactions', ['branch_id', 'product_id', 'created_at'], unique=False)
    op.create_table('invoice_adjustments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_invoice_adjustments_approved_by_id_users')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_invoice_adjustments_created_by_id_users')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_adjustments_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_adjustments'))
    )
    op.create_index(op.f('ix_invoice_adjustments_invoice_id'), 'invoice_adjustments', ['invoice_id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('line_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.CheckConstraint("line_type IN ('TABLE_TIME', 'MEMBERSHIP_COVERED', 'PRODUCT', 'DISCOUNT', 'TAX', 'DEPOSIT_CREDIT', 'FEE', 'ADJUSTMENT')", name=op.f('ck_invoice_lines_line_type')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_lines_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_invoice_lines_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_lines'))
    )
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    op.create_table('loyalty_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_loyalty_transactions_branch_id_branches')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_loyalty_transactions_customer_id_customers')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_loyalty_transactions_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loyalty_transactions'))
    )
    op.create_index(op.f('ix_loyalty_transactions_customer_id'), 'loyalty_transactions', ['customer_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('membership_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('provider_order_id', sa.String(length=80), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=80), nullable=True),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('refund_of_id', sa.Uuid(), nullable=True),
    sa.Column('received_by_id', sa.Uuid(), nullable=True),
    sa.Column('shift_id', sa.Uuid(), nullable=True),
    sa.Column('paid_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=300), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("method IN ('CASH', 'UPI', 'CARD', 'ONLINE', 'WALLET', 'CREDIT', 'MEMBERSHIP')", name=op.f('ck_payments_method')),
    sa.CheckConstraint("purpose IN ('BOOKING_DEPOSIT', 'INVOICE', 'MEMBERSHIP', 'DUE_SETTLEMENT', 'TOURNAMENT_FEE', 'REFUND')", name=op.f('ck_payments_purpose')),
    sa.CheckConstraint("status IN ('PENDING', 'AUTHORIZED', 'PAID', 'PARTIALLY_PAID', 'FAILED', 'REFUNDED', 'CANCELLED')", name=op.f('ck_payments_status')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_payments_booking_id_bookings')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_payments_branch_id_branches')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_payments_customer_id_customers')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_payments_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], name=op.f('fk_payments_membership_id_memberships')),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], name=op.f('fk_payments_received_by_id_users')),
    sa.ForeignKeyConstraint(['refund_of_id'], ['payments.id'], name=op.f('fk_payments_refund_of_id_payments')),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_payments_shift_id_shifts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_payments_idempotency_key')),
    sa.UniqueConstraint('provider', 'provider_payment_id', name=op.f('uq_payments_provider_provider_payment_id'))
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index('ix_payments_branch_paid', 'payments', ['branch_id', 'paid_at'], unique=False)
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_provider_order_id'), 'payments', ['provider_order_id'], unique=False)
    op.create_table('customer_ledger',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('payment_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("entry_type IN ('OPENING', 'CREDIT_SALE', 'PAYMENT', 'ADJUSTMENT', 'WALLET_TOPUP')", name=op.f('ck_customer_ledger_entry_type')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_customer_ledger_branch_id_branches')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_customer_ledger_created_by_id_users')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_ledger_customer_id_customers')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_customer_ledger_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_customer_ledger_payment_id_payments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_ledger'))
    )
    op.create_index(op.f('ix_customer_ledger_branch_id'), 'customer_ledger', ['branch_id'], unique=False)
    op.create_index('ix_customer_ledger_customer_created', 'customer_ledger', ['customer_id', 'created_at'], unique=False)
    op.create_foreign_key('fk_tournaments_winner_player_id_tournament_players', 'tournaments', 'tournament_players', ['winner_player_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (indexes are dropped together with their tables; explicit drop_index removed for MySQL FK compatibility)
    op.drop_constraint('fk_tournaments_winner_player_id_tournament_players', 'tournaments', type_='foreignkey')
    op.drop_table('customer_ledger')
    op.drop_table('payments')
    op.drop_table('loyalty_transactions')
    op.drop_table('invoice_lines')
    op.drop_table('invoice_adjustments')
    op.drop_table('inventory_transactions')
    op.drop_table('approval_requests')
    op.drop_table('order_items')
    op.drop_table('invoices')
    op.drop_table('session_pauses')
    op.drop_table('session_events')
    op.drop_table('orders')
    op.drop_table('membership_transactions')
    op.drop_table('alerts')
    op.drop_table('game_sessions')
    op.drop_table('expenses')
    op.drop_table('booking_holds')
    op.drop_table('user_roles')
    op.drop_table('tournament_matches')
    op.drop_table('table_detection_states')
    op.drop_table('shifts')
    op.drop_table('refresh_tokens')
    op.drop_table('device_heartbeats')
    op.drop_table('device_events')
    op.drop_table('bookings')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('tournament_players')
    op.drop_table('pricing_rules')
    op.drop_table('notifications')
    op.drop_table('memberships')
    op.drop_table('devices')
    op.drop_table('tournaments')
    op.drop_table('tables')
    op.drop_table('system_settings')
    op.drop_table('stock_levels')
    op.drop_table('holidays')
    op.drop_table('document_sequences')
    op.drop_table('customers')
    op.drop_table('role_permissions')
    op.drop_table('products')
    op.drop_table('branches')
    op.drop_table('suppliers')
    op.drop_table('roles')
    op.drop_table('product_categories')
    op.drop_table('notification_templates')
    op.drop_table('membership_plans')
    op.drop_table('game_types')
    op.drop_table('expense_categories')
    op.drop_table('coupons')
    op.drop_table('clubs')
    op.drop_table('permissions')
    op.drop_table('payment_webhook_events')
    op.drop_table('organizations')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
